name: Build OpenWrt with SSR Plus and tmate SSH

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    name: Compile OpenWrt
    steps:

    - name: Checkout Source
      uses: actions/checkout@v4

    - name: 释放磁盘空间
      uses: jlumbroso/free-disk-space@main
      with:
        # this might remove tools that are actually needed,
        # if set to "true" but frees about 6 GB
        tool-cache: true
        # all of these default to true, but feel free to set to
        # "false" if necessary for your workflow
        android: true
        dotnet: true
        haskell: true
        large-packages: true
        swap-storage: true

    - name: Set up Environment
      run: |
        sudo apt-get update
        sudo apt-get install -y git-core build-essential libssl-dev libncurses5-dev unzip gawk zlib1g-dev subversion wget python3 python3-distutils rsync

    - name: Clone Official OpenWrt
      run: |
        git clone https://github.com/openwrt/openwrt.git
        cd openwrt
        ./scripts/feeds update -a
        ./scripts/feeds install -a

    - name: Add SSR Plus Feed
      run: |
        echo "src-git helloworld https://github.com/fw876/helloworld" >> openwrt/feeds.conf.default
        cd openwrt
        ./scripts/feeds update helloworld
        ./scripts/feeds install -a

    - name: Copy Custom Config
      run: |
        cp .config openwrt/.config

    - name: tmate SSH Debug Session (optional)
      if: always()
      uses: mxschmitt/action-tmate@v3
      timeout-minutes: 60

    - name: Compile Firmware
      run: |
        cd openwrt
        make defconfig
        make download -j$(nproc) || true
        make -j$(nproc)

    - name: Upload Firmware
      uses: actions/upload-artifact@v4
      with:
        name: OpenWrt_firmware
        path: openwrt/bin/targets

















